#
[[main]]
identifier = "home"
weight = 1
pageRef = "/"
params = { icon = "icons/home.svg" }

#
[[main]]
identifier = "students"
weight = 3
pageRef = "/studierende"
params = { icon = "icons/school.svg" }

[[main]]
identifier = "examregulations"
weight = 1
parent = "students"
pageRef = "/studierende/pos"

[[main]]
identifier = "nkt"
weight = 2
parent = "students"
pageRef = "/studierende/nkt"

#
[[main]]
identifier = "subscripts"
weight = 4
pageRef = "/protokolle"
params = { icon = "icons/script.svg" }

#
[[main]]
identifier = "aboutus"
weight = 100
pageRef = "/about"
params = { icon = "icons/question-mark.svg" }
