# modules
[module]
[module.hugoVersion]
extended = true

# we have to explicitly mount these, otherwise they just disappear. dont really know why
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "layouts"
target = "layouts"
[[module.mounts]]
source = "i18n"
target = "i18n"
[[module.mounts]]
source = "static"
target = "static"

# include our icons
[[module.imports]]
path = "github.com/tabler/tabler-icons"
[[module.imports.mounts]]
source = "icons"
target = "assets/icons/"

# include bootstrap
[[module.imports]]
path = "github.com/twbs/bootstrap"
ignoreConfig = true
[[module.imports.mounts]]
source = "scss"
target = "assets/scss/bootstrap"
[[module.imports.mounts]]
source = "js"
target = "assets/js/bootstrap"
[[module.mounts]]
source = "bootstrap"
target = "assets/scss/bootstrap/vendor"

# include popperjs, a library required by bootstrap
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-jslibs-dist/popperjs/v2"
